name: Paulo
favicon: null
layout_spectrum: 0.4432568307965994
typography_spectrum: 0.8864423967897892
title: Paulo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4337996509857476
  lightness: 0.5156934931874275
  saturation: 0.9385620029643178
  rhythmicContrast: 0.24986977339722216
purpose: []
